working_directory = "C:\\Users\\dev\\git"

[shell]
program = "cmd.exe"
args = ["%comspec% /k \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\Tools\\VsDevCmd.bat\""]

[window]
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
